---
application:
  name: "ytdl-server"
  project: "ytdl-server"
  organization: "QoveryCommunity"
  publicly_accessible: true
  cpu: 2
  port: 8080
  ram: 1GB
  storage:
  - name: "ytdl-server"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/ytdl-server"
routers:
- name: "main-ytdl-server"
  routes:
  - application_name: "ytdl-server"
    paths:
    - "/*"
